/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projekt;

import java.awt.Color;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;
import com.sdz.observer.*;

/**
 *
 * @author root
 */
public class GUI extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form view
     */
    public GUI() {
        initComponents();
    }
 public void setbackgrundcolor(Color color1){
 varf.setForeground(color1);
 
 }
public void setstationid(String id) {
stationidf.setText(id);
}
public void setactule(int act) {
actulef.setText(String.valueOf(act));
}
public void settrg(int trg) {
targetf.setText(String.valueOf(trg));
}
public void setdate(String date) {
Sdate.setText(date);
}
public void setvar(int var) {
    if((var*-1)<0){
varf.setText(String.valueOf(var*-1));
}
    if((var*-1)>0){
varf.setText("+"+String.valueOf(var*-1));
}
}
public void setjlist(DefaultListModel listModel ){
        StationListF.setModel(listModel);}
void selected(ListSelectionListener listenForCalcButton){
		
		StationListF.addListSelectionListener(listenForCalcButton);
		
	}
public String getselected(){
 String selected = StationListF.getSelectedValue();
return selected;
}
public void settext(String selected)
        {
        
        stationidname.setText(selected);
           
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        StationListF = new javax.swing.JList<>();
        Sdate = new javax.swing.JTextField();
        targetf = new javax.swing.JTextField();
        varf = new javax.swing.JTextField();
        actulef = new javax.swing.JTextField();
        stationidf = new javax.swing.JTextField();
        stationidname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StationListF.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        StationListF.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(StationListF);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 370));

        Sdate.setBackground(new java.awt.Color(240, 241, 245));
        Sdate.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        Sdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sdate.setBorder(null);
        getContentPane().add(Sdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 125, 240, 40));

        targetf.setBackground(new java.awt.Color(240, 241, 245));
        targetf.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        targetf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        targetf.setBorder(null);
        getContentPane().add(targetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 193, 240, 40));

        varf.setBackground(new java.awt.Color(240, 241, 245));
        varf.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        varf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        varf.setBorder(null);
        getContentPane().add(varf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 328, 240, 40));

        actulef.setBackground(new java.awt.Color(240, 241, 245));
        actulef.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        actulef.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        actulef.setBorder(null);
        getContentPane().add(actulef, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 240, 40));

        stationidf.setBackground(new java.awt.Color(240, 241, 245));
        stationidf.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        stationidf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        stationidf.setBorder(null);
        getContentPane().add(stationidf, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 240, 40));

        stationidname.setFont(new java.awt.Font("Bitstream Vera Sans", 3, 18)); // NOI18N
        stationidname.setForeground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        stationidname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stationidname.setText("Station List");
        stationidname.setToolTipText("");
        getContentPane().add(stationidname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 40));

        jLabel1.setText("backgrundL");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Sdate;
    private javax.swing.JList<String> StationListF;
    private javax.swing.JTextField actulef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stationidf;
    private javax.swing.JLabel stationidname;
    private javax.swing.JTextField targetf;
    private javax.swing.JTextField varf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void aktualisiere(String str) {
        notify alt = new notify();
       alt.created();
       alt.setVisible(true);
    }

  
   

  

    

    
}
